# Dependencies
markdown:         redcarpet

# Setup
title:            mingi's blog
url:              https://midaslmg94.github.io/
baseurl:          ""

author:
  name:           'mgLee'
  email:          midaslmg94@gmail.com
paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/midaslmg94/midaslmg94.github.io
